---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-sql-updates
spec:
  template:
    metadata:
      name: apply-sql-updates
    spec:
      containers:
        - name: apply-sql-updates
          image: tigervin/ignite-apply-sql-updates-job
          args: ["-url=jdbc:sqlserver://<Server>;database=master", "-user=sa", "-password=yourStrongPassw0rd!", "-mixed=true", "migrate"]
      restartPolicy: Never